### ISSUE TITLE
buttplug library out of date new hardware not supported

### ISSUE THREAD

**Issue by brodokk** [runtime-shady-backroom/buttplug-lite#10]
There is new hardware support since the version 5.1.0 of buttplug library https://github.com/buttplugio/buttplug/blob/51e0bba369f760ae704fa3d672c0a17791681226/buttplug/CHANGELOG.md#510-2021-12-01

**Comment by runtime-shady-backroom** [comment]
Thanks for the heads up! The new [0.8.0](https://github.com/runtime-shady-backroom/buttplug-lite/releases/tag/0.8.0) release pulls in the current version of buttplug. I'm always happy to update dependencies as (usually) it's a very simple change.

Trivia time: originally this project used intiface-desktop as a backend, which was nice because it supports auto-updating buttplug. But I received feedback that people didn't like installing and running two different programs, so I switched over to including the whole buttplug backend in my application. The downside? No more auto updates.
