### ISSUE TITLE
wgpu: Validation Error

### ISSUE THREAD

**Issue by TheNull** [runtime-shady-backroom/buttplug-lite#12]
buttplug-lite is crashing on startup with the following error:

```
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 1, Vulkan)>`
    In a set_scissor_rect command
    Invalid ScissorRect parameters


thread 'main' panicked at 'Handling wgpu errors as fatal by default', C:\Users\michael\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.7.0\src\backend\direct.rs:1896:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Running on Windows 10 19044.1889

**Comment by runtime-shady-backroom** [comment]
Thanks for the bug report. This looks like the GUI library I'm using is having some sort of issue. My thoughts are I should update buttplug-lite to the most recent version of the GUI library and we'll see if the issue persists. If it does, then I'll probably need to open a bug report with the library maintainers.

It's been four months since I'v looked at buttplug-lite, so give me some time to dust off my dev branch and get my library dependencies updated. I'll get a new build for you to test Soon™.

**Comment by runtime-shady-backroom** [comment]
@TheNull Please test with [version 1.0.1](https://github.com/runtime-shady-backroom/buttplug-lite/releases/tag/1.0.1) and let me know how it goes.

**Comment by TheNull** [comment]
This seems to have been resolved by the update, thanks for the quick response!
