### ISSUE TITLE
Suggest rebuild to support Buttplug.io 7.1.16 due to Solace bug

### ISSUE THREAD

**Issue by dragos240** [runtime-shady-backroom/buttplug-lite#158]
**Describe the bug**
The Solace will not stop running unless the build is updated to 7.1.16, even if it's given a value of 0.0. See https://github.com/buttplugio/buttplug/commit/d1469690e7c9d4af45ba89a40be6973db5643a5f

**To Reproduce**
- Connect a Lovense Solace, send a value of 0.0, it will start moving.

**Expected behavior**
The Solace should stop given a zero value

**Screenshots**
N/A

**Desktop (please complete the following information):**
All

**Additional context**
I suggest merging https://github.com/runtime-shady-backroom/buttplug-lite/pull/154

**Comment by runtime-shady-backroom** [comment]
Thanks for taking the time to open this issue; it's nice to know folks are still getting some use out of my software :)

I've updated to buttplug 7.1.16 in [buttplug-lite 2.5.2](https://github.com/runtime-shady-backroom/buttplug-lite/releases/tag/2.5.2). I wanted to go all the way to buttplug 8.0.0, but it's giving me some issues I haven't figured out yet, so that'll have to wait for another day.
