### ISSUE TITLE
Windows Security labels as Trojan with 2.4.0 .exe

### ISSUE THREAD

**Issue by Wolfscopez** [runtime-shady-backroom/buttplug-lite#65]
**Describe the bug**
Windows Security labels the program as very dangerous and labels it a Trojan Wacatac.B!ml

**To Reproduce**
1. Download latest .exe for windows
2. Fin

**Expected behavior**
Previous .exe's have not triggered this response, version 2.0.1 works with no trojan alert.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Comment by Wolfscopez** [comment]
For reference 2.3.0 does not trigger this response from Windows Security, but 2.4.0 immediately makes it delete the executable automatically.

**Comment by runtime-shady-backroom** [comment]
I'm pretty sure this is a false positive, as I can't reproduce the detection.

## Things you can try

- Update your antivirus definitions
- Try a different build of the same executable. You can go grab the `buttplug-lite-x86_64-pc-windows-msvc` artifact from the bottom of [this CI build](https://github.com/runtime-shady-backroom/buttplug-lite/actions/runs/4449199920). It's the exact same source code, but a different SHA256 hash (`4c473336e572961362c586704324b6d5916bbcbab974d152064271ee3bce58e7`) because Rust builds aren't reproducible.
- Whitelist buttplug-lite-windows.exe in your antivirus
- Compile it yourself. I've added [steps to build from source](https://github.com/runtime-shady-backroom/buttplug-lite#building-from-source) to the readme.

## My checks

I've ran some testing against [2.4.0 buttplug-lite-windows.exe](https://github.com/runtime-shady-backroom/buttplug-lite/releases/download/2.4.0/buttplug-lite-windows.exe), which has the SHA256 checksum `367ce270271513ef1806b61670da309f3a190546cb846aee9775e8073ea67750`.

I've downloaded the executable myself and only got the SmartScreen warning:

![image](https://user-images.githubusercontent.com/76618880/225947442-f4a13549-a852-41f8-9a38-20e3fd5d7f84.png)

There's not much I can do about SmartScreen, because it's mad I don't have a code-signing certificate. I'm not interested in getting a code-signing cert presently because:
- Certs are upwards of ~$70 a year, which is ridiculous to support one free open-source project.
- It would expose my real name, and I'm not quite to the point in my life where I want that tied directly to buttplug software. I'd rather my present and future employers have to stalk me a *little* harder than that to make the connection.

Going further, Microsoft Defender 1.385.297.0 doesn't mind it, letting me run the executable just fine. I also explicitly had Defender scan it and it still doesn't mind. I'm on Windows 10 Home 22H2. No idea why Defender would behave differently on Win11.

Finally, I've uploaded the executable to [VirusTotal](https://www.virustotal.com/gui/file/367ce270271513ef1806b61670da309f3a190546cb846aee9775e8073ea67750/detection), and none of its detections triggered.

Diffing https://github.com/runtime-shady-backroom/buttplug-lite/compare/2.3.0...2.4.0 nothing super weird changed. I added a panic handler and updated a bunch of dependencies. It's possible that one of those dependencies introduced malware, but unlikely. I've re-ran an audit of buttplug-lite's dependencies to make sure there are no known [RustSec](https://rustsec.org/) advisories. GitHub should have emailed me if there were... but this gives me a full report. You can see that report [here](https://github.com/runtime-shady-backroom/buttplug-lite/actions/runs/4449199920/jobs/7813038987) in the `cargo-deny-action` step if you like reading spooky logs.

**Comment by Wolfscopez** [comment]
Downloaded the application again and Windows didn't flag it this time around, seems like it's not treating it like a trojan anymore

**Comment by runtime-shady-backroom** [comment]
As this is no longer reproducible I'm closing the issue. It's not really something I can do anything about anyways.
